DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PWD"	VARCHAR2(20)		NOT NULL,
	"NAME"	VARCHAR2(60)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NULL,
	"PHONE"	CHAR(11)		NULL,
	"AGREE"	NUMBER	DEFAULT 0	NOT NULL,
	"ADMIN"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."ID" IS '영문소문자 숫자,4~16자';

COMMENT ON COLUMN "MEMBER"."PWD" IS '영문 숫자 특수문자 중 2가지 이상,  10~16자';

COMMENT ON COLUMN "MEMBER"."NAME" IS '2자 이상, 20자 이하';

COMMENT ON COLUMN "MEMBER"."AGREE" IS '1동의 =1, 2동의=2 1 2동의=3 비동의=0';

COMMENT ON COLUMN "MEMBER"."ADMIN" IS '관리자 = Y   일반회원 = N';

DROP TABLE "CREATOR";

CREATE TABLE "CREATOR" (
	"CNO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"CNAME"	VARCHAR2(60)		NOT NULL,
	"CINFO"	VARCHAR2(900)		NULL
);

COMMENT ON COLUMN "CREATOR"."ID" IS '영문소문자 숫자,4~16자';

DROP TABLE "PROJECT";

CREATE TABLE "PROJECT" (
	"PNO"	NUMBER		NOT NULL,
	"CNO"	NUMBER		NOT NULL,
	"CATENO"	CHAR(20)		NOT NULL,
	"PJTITLE"	VARCHAR2(100)		NOT NULL,
	"PJSTITLE"	VARCHAR2(20)		NOT NULL,
	"PJSUM"	VARCHAR2(200)		NOT NULL,
	"PJTAG"	VARCHAR2(500)		NULL,
	"TGMONEY"	NUMBER		NOT NULL,
	"SDAY"	DATE		NOT NULL,
	"FDAY"	DATE		NOT NULL,
	"TDAY"	DATE		NOT NULL,
	"PERMISSION"	CHAR(1)	DEFAULT N	NOT NULL
);

COMMENT ON COLUMN "PROJECT"."PJTITLE" IS '긴제목';

COMMENT ON COLUMN "PROJECT"."PJSTITLE" IS '짧은제목';

COMMENT ON COLUMN "PROJECT"."PJTAG" IS '쉼표,문자만 최소 2글자 이상';

COMMENT ON COLUMN "PROJECT"."PERMISSION" IS '미승인 = N  승인 = Y';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
	"CATENO"	CHAR(20)		NOT NULL,
	"CATENAME"	VARCHAR2(100)		NOT NULL,
	"DETAILCATE"	VARCHAR2(100)		NOT NULL
);

DROP TABLE "PJFILE";

CREATE TABLE "PJFILE" (
	"PNO"	NUMBER		NOT NULL,
	"FILENAME"	VARCHAR2(500)		NULL
);

DROP TABLE "PROJECTPLAN";

CREATE TABLE "PROJECTPLAN" (
	"PNO"	NUMBER		NOT NULL,
	"PJINFO"	VARCHAR2(2000)		NOT NULL,
	"PJBUDGET"	VARCHAR2(1000)		NOT NULL,
	"PJSCHEDULE"	VARCHAR2(1000)		NOT NULL,
	"PJTEAMINFO"	VARCHAR2(1000)		NOT NULL,
	"FUTURESINFO"	VARCHAR2(1000)		NOT NULL
);

DROP TABLE "FUTURES";

CREATE TABLE "FUTURES" (
	"FNO"	NUMBER		NOT NULL,
	"PNO"	NUMBER		NOT NULL,
	"FNAME"	VARCHAR2(100)		NOT NULL,
	"FPRICE"	NUMBER		NOT NULL,
	"FSTOCK"	NUMBER		NULL
);

DROP TABLE "FSELECTION";

CREATE TABLE "FSELECTION" (
	"FNO"	NUMBER		NOT NULL,
	"FUNNO"	NUMBER		NOT NULL,
	"ADDFUN"	NUMBER		NULL
);

DROP TABLE "FUNDING";

CREATE TABLE "FUNDING" (
	"FUNNO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"FADDRESS"	VARCHAR2(100)		NOT NULL,
	"RECIPIENT"	VARCHAR2(60)		NOT NULL
);

COMMENT ON COLUMN "FUNDING"."ID" IS '영문소문자,숫자,4~16자';

DROP TABLE "PLIKE";

CREATE TABLE "PLIKE" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PNO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PLIKE"."ID" IS '영문소문자,숫자,4~16자';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "CREATOR" ADD CONSTRAINT "PK_CREATOR" PRIMARY KEY (
	"CNO",
	"ID"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
	"PNO",
	"CNO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATENO"
);

ALTER TABLE "PROJECTPLAN" ADD CONSTRAINT "PK_PROJECTPLAN" PRIMARY KEY (
	"PNO"
);

ALTER TABLE "FUTURES" ADD CONSTRAINT "PK_FUTURES" PRIMARY KEY (
	"FNO"
);

ALTER TABLE "FUNDING" ADD CONSTRAINT "PK_FUNDING" PRIMARY KEY (
	"FUNNO",
	"ID"
);

ALTER TABLE "CREATOR" ADD CONSTRAINT "FK_MEMBER_TO_CREATOR_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "FK_CREATOR_TO_PROJECT_1" FOREIGN KEY (
	"CNO"
)
REFERENCES "CREATOR" (
	"CNO"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "FK_CATEGORY_TO_PROJECT_1" FOREIGN KEY (
	"CATENO"
)
REFERENCES "CATEGORY" (
	"CATENO"
);

ALTER TABLE "PJFILE" ADD CONSTRAINT "FK_PROJECT_TO_PJFILE_1" FOREIGN KEY (
	"PNO"
)
REFERENCES "PROJECT" (
	"PNO"
);

ALTER TABLE "PROJECTPLAN" ADD CONSTRAINT "FK_PROJECT_TO_PROJECTPLAN_1" FOREIGN KEY (
	"PNO"
)
REFERENCES "PROJECT" (
	"PNO"
);

ALTER TABLE "FUTURES" ADD CONSTRAINT "FK_PROJECT_TO_FUTURES_1" FOREIGN KEY (
	"PNO"
)
REFERENCES "PROJECT" (
	"PNO"
);

ALTER TABLE "FSELECTION" ADD CONSTRAINT "FK_FUTURES_TO_FSELECTION_1" FOREIGN KEY (
	"FNO"
)
REFERENCES "FUTURES" (
	"FNO"
);

ALTER TABLE "FSELECTION" ADD CONSTRAINT "FK_FUNDING_TO_FSELECTION_1" FOREIGN KEY (
	"FUNNO"
)
REFERENCES "FUNDING" (
	"FUNNO"
);

ALTER TABLE "FUNDING" ADD CONSTRAINT "FK_MEMBER_TO_FUNDING_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "PLIKE" ADD CONSTRAINT "FK_MEMBER_TO_PLIKE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "MEMBER" (
	"ID"
);

ALTER TABLE "PLIKE" ADD CONSTRAINT "FK_PROJECT_TO_PLIKE_1" FOREIGN KEY (
	"PNO"
)
REFERENCES "PROJECT" (
	"PNO"
);

